name: JOPHWarn
main: me.jophestus.JOPHWarn.JOPHWarn
version: 2.0
author: JOPHESTUS
description: Warns players for misconduct
commands:
    warn:
        description: Warns a player
    warnings:
        description: Views a players warnings
    jophwarn:
        description: Shows information about the plugin
    infract:
        description: Gives a player a fraction
    infractions:
        description: Views a players infractions
    confirm:
        description: Used to infract a user when they already have warnings when you warn them
    deny:
        description: Used to warn a user upon being asked if you want to infract when they already have warnings when you warn them